/** Visual theme tokens for @react-pdf/renderer layouts. */
export const PDF_THEMES = {
    Professional: {
        fontFamily: 'Helvetica',
        headingFont: 'Helvetica-Bold',
        page: { backgroundColor: '#ffffff', color: '#333333' },
        name: { color: '#1a365d', size: 24 },
        profession: { color: '#4a5568', size: 13 },
        contact: { color: '#4b5563', size: 9 },
        sectionTitle: { color: '#1a365d', size: 11, border: '#e2e8f0' },
        body: { color: '#333333', size: 9.5 },
        accent: '#1a365d',
        headerStyle: 'center',
    },
    Minimalist: {
        fontFamily: 'Helvetica',
        headingFont: 'Helvetica-Bold',
        page: { backgroundColor: '#ffffff', color: '#1a1a1a' },
        name: { color: '#000000', size: 20 },
        profession: { color: '#666666', size: 10 },
        contact: { color: '#777777', size: 8.5 },
        sectionTitle: { color: '#555555', size: 8.5, border: '#eeeeee' },
        body: { color: '#333333', size: 9 },
        accent: '#cccccc',
        headerStyle: 'center',
    },
    America: {
        fontFamily: 'Helvetica',
        headingFont: 'Helvetica-Bold',
        page: { backgroundColor: '#ffffff', color: '#333333' },
        name: { color: '#000000', size: 20 },
        profession: { color: '#666666', size: 11 },
        contact: { color: '#444444', size: 9 },
        sectionTitle: { color: '#000000', size: 11, border: '#dddddd' },
        body: { color: '#333333', size: 9.5 },
        accent: '#000000',
        headerStyle: 'center',
    },
    Gulf: {
        fontFamily: 'Helvetica',
        headingFont: 'Helvetica-Bold',
        layout: 'gulf',
        page: { backgroundColor: '#ffffff', color: '#1e293b' },
        headerBand: { backgroundColor: '#1e293b', color: '#ffffff' },
        name: { color: '#ffffff', size: 22 },
        profession: { color: '#94a3b8', size: 11 },
        contact: { color: '#cbd5e1', size: 9 },
        sectionTitle: { color: '#334155', size: 10, border: '#e2e8f0' },
        body: { color: '#1e293b', size: 9.5 },
        accent: '#1e293b',
        headerStyle: 'gulf',
    },
    European: {
        fontFamily: 'Helvetica',
        headingFont: 'Helvetica-Bold',
        layout: 'sidebar',
        page: { backgroundColor: '#ffffff', color: '#334155' },
        sidebar: { backgroundColor: '#0f172a', color: '#ffffff', width: 170 },
        sidebarAccent: '#3498db',
        name: { color: '#1e293b', size: 20 },
        profession: { color: '#64748b', size: 11 },
        contact: { color: '#e2e8f0', size: 8.5 },
        sectionTitle: { color: '#1e293b', size: 12, border: '#f1f5f9' },
        body: { color: '#334155', size: 9.5 },
        accent: '#3498db',
        headerStyle: 'main',
    },
    Creative: {
        fontFamily: 'Helvetica',
        headingFont: 'Helvetica-Bold',
        layout: 'sidebar',
        page: { backgroundColor: '#f8fafc', color: '#1e293b' },
        sidebar: { backgroundColor: '#ffffff', color: '#1e293b', width: 160 },
        sidebarAccent: '#6366f1',
        name: { color: '#ffffff', size: 22 },
        profession: { color: '#ffffff', size: 12 },
        contact: { color: '#1e293b', size: 8.5 },
        sectionTitle: { color: '#1e293b', size: 13, border: '#6366f1' },
        body: { color: '#334155', size: 9.5 },
        accent: '#6366f1',
        headerStyle: 'creative',
        headerBand: { backgroundColor: '#6366f1', color: '#ffffff' },
    },
    Executive: {
        fontFamily: 'Times-Roman',
        headingFont: 'Times-Bold',
        page: { backgroundColor: '#ffffff', color: '#1a202c' },
        name: { color: '#1a202c', size: 20 },
        profession: { color: '#4a5568', size: 11 },
        contact: { color: '#4b5563', size: 9 },
        sectionTitle: { color: '#2d3748', size: 11, border: '#cbd5e0' },
        body: { color: '#1a202c', size: 10 },
        accent: '#2d3748',
        headerStyle: 'executive',
    },
    Academic: {
        fontFamily: 'Times-Roman',
        headingFont: 'Times-Bold',
        page: { backgroundColor: '#ffffff', color: '#000000' },
        name: { color: '#000000', size: 18 },
        profession: { color: '#444444', size: 10 },
        contact: { color: '#444444', size: 9 },
        sectionTitle: { color: '#000000', size: 11, border: '#000000' },
        body: { color: '#000000', size: 10 },
        accent: '#000000',
        headerStyle: 'center',
    },
    Tech: {
        fontFamily: 'Helvetica',
        headingFont: 'Helvetica-Bold',
        layout: 'tech',
        page: { backgroundColor: '#0f172a', color: '#94a3b8' },
        name: { color: '#f8fafc', size: 20 },
        profession: { color: '#38bdf8', size: 10 },
        contact: { color: '#38bdf8', size: 8.5 },
        sectionTitle: { color: '#fbbf24', size: 10, border: '#1e293b', prefix: '// ', uppercase: false, fontFamily: 'Courier', letterSpacing: 0 },
        body: { color: '#cbd5e1', size: 9 },
        accent: '#38bdf8',
        headerStyle: 'tech',
        bullet: { char: '>', color: '#38bdf8', width: 10 },
    },
    Service: {
        fontFamily: 'Helvetica',
        headingFont: 'Helvetica-Bold',
        page: { backgroundColor: '#ffffff', color: '#444444' },
        name: { color: '#334155', size: 20 },
        profession: { color: '#64748b', size: 10 },
        contact: { color: '#64748b', size: 9 },
        sectionTitle: { color: '#ffffff', size: 10, border: '#334155', fill: '#334155' },
        body: { color: '#444444', size: 9.5 },
        accent: '#334155',
        headerStyle: 'center',
    },
    Plain: {
        fontFamily: 'Helvetica',
        headingFont: 'Helvetica-Bold',
        page: { backgroundColor: '#ffffff', color: '#1a1a1a' },
        name: { color: '#1a1a1a', size: 20 },
        profession: { color: '#555555', size: 11 },
        contact: { color: '#555555', size: 9 },
        sectionTitle: { color: '#555555', size: 10, border: '#e5e5e5' },
        body: { color: '#1a1a1a', size: 10 },
        accent: '#555555',
        headerStyle: 'center',
    },
};

export function getPdfTheme(format) {
    return PDF_THEMES[format] || PDF_THEMES.Professional;
}
